# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-24 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d')),
                ('AddTime', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='CourceResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('Download', models.FileField(upload_to='cource/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6')),
                ('AddTime', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d')),
                ('Desc', models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('Detail', models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5')),
                ('Degree', models.CharField(choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], max_length=2)),
                ('LearnTimes', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206\u949f)')),
                ('Students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('FavNumbers', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('Image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('ClickNumbers', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('AddTime', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d')),
                ('AddTime', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Chapter', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
        migrations.AddField(
            model_name='courceresource',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course', verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
